set(TINYXML_VERSION 2.6.2 CACHE INTERNAL "")
set(TINYXML_COMPILER cl CACHE INTERNAL "")
set(TINYXML_COMPILER_VERSION 16.0 CACHE INTERNAL "")
set(TINYXML_BUILD_MODE Release CACHE INTERNAL "")

get_filename_component(TINYXML_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

set(TINYXML_INCLUDE_DIR "${TINYXML_CMAKE_DIR}/../../../include" CACHE PATH "Tinyxml include directory")
set(TINYXML_INCLUDE_DIRS "${TINYXML_INCLUDE_DIR}" CACHE INTERNAL "")
set(TINYXML_LIBRARY_DIRS "${TINYXML_CMAKE_DIR}/../../../lib" CACHE INTERNAL "")
set(TINYXML_LIBRARIES "${TINYXML_CMAKE_DIR}/../../../lib/tinyxml.lib" CACHE INTERNAL "")